blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from myblog.sitemaps import PostSitemap
from django.conf.urls.static import static
from django.conf import settings


sitemaps = {
	'posts': PostSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls', namespace='myblog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name = 'django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import path
from . import views
from myblog.feeds import LatestPostFeed

app_name = 'myblog'

urlpatterns = [
	# path('', views.post_list, name='post_list')
	# path('', views.PostListView.as_view(), name='post_list'),
	path('<int:post_id>/share/', views.post_share, name='post_share'),
	path('', views.Blog.as_view(), name='blog'),
	path('index/', views.index, name='index'),
	path('<category>/<slug:post>/', views.blogdetail, name='blogdetail'),
	# path('blog/', views.blog, name='index'),
	# path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
	path('feed/', LatestPostFeed(), name='post_feed'),
]

myblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
		STATUS_CHOICE = (('draft', 'Draft'),('published', 'Published'))
		CATEGORY_CHOICE = (('datascience', 'Data Science'),('machinelearning', 'Machine Learning'))
		title 		  = models.CharField(max_length=250)
		slug 		  = models.SlugField(max_length=100, unique_for_date='publish')
		author 		  = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
		image         = models.ImageField(upload_to='blog_images/', default='/blog_images/default.jpg')
		body 		  = models.TextField()
		category	  = models.CharField(max_length=20, choices=CATEGORY_CHOICE, default='datascience')
		publish 	  = models.DateTimeField(default=timezone.now)
		created 	  = models.DateTimeField(auto_now_add=True)
		updated 	  = models.DateTimeField(auto_now=True)
		status 	      = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
		tags		  = TaggableManager()

		objects = models.Manager()
		published = PublishedManager()

		# def get_absolute_url(self):
		# 	return reverse('myblog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

		def get_absolute_url(self):
			return reverse('myblog:blogdetail', args=[self.category, self.slug])

		class Meta:
			ordering = ('-publish',)

		def __str__(self):
				return self.title

class Comment(models.Model):
		post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
		name = models.CharField(max_length=75)
		email = models.EmailField()
		body = models.TextField()
		created = models.DateTimeField(auto_now_add=True)
		updated = models.DateTimeField(auto_now=True)
		active = models.BooleanField(default=True)

		class Meta:
			ordering = ('created',)

		def __str__(self):
			return 'Comment by {} on {}'.format(self.name, self.post)

myblog/forms.py
from django import forms
from .models import Comment

class PostShareToEmail(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

myblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import PostShareToEmail, CommentForm
from django.core.mail import send_mail

# def post_list(request):
# 	posts = Post.published.all()
	# paginator = Paginator(posts, 3)
	# page = request.GET.get('page')
	# try:
	# 	posts = paginator.page(page)
	# except PageNotAnInteger:
	# 	posts = paginator.page(1)
	# except EmptyPage:
	# 	posts = paginator.page(paginator.num_pages)
# 	return render(request, 'myblog/blog.html', {'posts' : posts, 'page' : page})

# class PostListView(ListView):
# 	queryset = Post.published.all()
# 	context_object_name = 'posts'
# 	paginate_by = 3
# 	template_name = 'myblog/post/list.html'

# def post_detail(request, year, month, day, post):
# 	post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

# 	return render(request, 'myblog/post/detail.html', {'post': post})


# NEW PART
def index(request):
	return render(request, 'myblog/index.html')

def blogdetail(request, category, post):
	post = get_object_or_404(Post, slug=post, status='published', category=category)

	comments = post.comments.filter(active=True)
	new_comment = None

	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()
	return render(request, 'myblog/post.html', {'post': post,
												'comments': comments,
												'new_comment': new_comment,
												'comment_form': comment_form})

class Blog(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 4
	template_name = 'myblog/blog.html'

def post_share(request, post_id):
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False

	if request.method == 'POST':
		form = PostShareToEmail(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'talk2manoz@gmail.com', [cd['to']])
			sent = True

	else:
		form = PostShareToEmail()
	return render(request, 'myblog/share.html', {'post': post,
												 'form': form,
												 'sent': sent})

myblog/templates/myblog/blog.html
{% extends 'myblog/header.html' %}
{% load blog_tags %}
{% load static %}
{% block main %}
<div class="container">
    <div class="row">
        <main class="posts-listing col-lg-8">
            <div class="container">
                <strong>This is my personal blog. I've written {% total_posts %} posts so far.</strong>
                <p class="mb-3"><a href="{% url 'myblog:post_feed' %}">Subscribe to my RSS feed.</a></p>
                <div class="row">
                    {% for post in posts %}
                    <div class="post col-xl-6">
                        <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt="..." class="img-fluid"></a></div>
                        <div class="post-details">
                            <div class="post-meta d-flex justify-content-between">
                                <div class="date meta-last">{{ post.publish }}</div>
                                <div class="category"><a href="#">{{ post.category }}</a></div>
                            </div><a href="{{ post.get_absolute_url }}">
                                <h3 class="h4">{{ post.title }}</h3>
                            </a>
                            <p class="text-muted">{{ post.body | truncatewords:20 }}</p>
                            <p class="post-tags">Tags:<a href="#" class="tag">{{ post.tags.all | join:", " }}</a></p>
                            <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                                    <div class="avatar"><img src="{% static 'img/avatar-3.jpg' %}" alt="..." class="img-fluid"></div>
                                    <div class="title"><span>{{ post.author }}</span></div>
                                </a>
                                <div class="date"><i class="icon-clock"></i> 2 months ago</div>
                                <div class="comments meta-last"><i class="icon-comment"></i>12</div>
                            </footer>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% include "myblog/pagination.html" with page=page_obj %}
            </div>
        </main>
        <aside class="col-lg-4">
            <!-- Widget [Latest Posts Widget]        -->
            <div class="widget latest-posts">
                <header>
                    <h3 class="h6">Latest Posts</h3>
                </header>
                {% show_latest_posts 3 %}
            </div>
            <div class="widget latest-posts">
                <header>
                    <h3 class="h6">Most Commented Posts</h3>
                </header>
                <div class="blog-posts">
                    {% get_most_commented_posts as most_commented_posts %}
                    {% for post in most_commented_posts %}
                    <a href="{{ post.get_absolute_url }}">
                        <div class="item d-flex align-items-center">
                            <div class="image"><img src="{{ post.image.url }}" alt="..." class="img-fluid"></div>
                            <div class="title"><strong>{{ post.title }}</strong>
                                <div class="d-flex align-items-center">
                                    <div class="comments"><i class="icon-comment"></i>{{ post.comments.count }}</div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </a></div>
            </div>
        </aside>
    </div>
</div>
{% endblock %}

myblog/templates/myblog/header.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Blog - B4 Template by Bootstrap Temple</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>

<body>
    <header class="header">
        <!-- Main Navbar-->
        <nav class="navbar navbar-expand-lg">
            <div class="search-area">
                <div class="search-area-inner d-flex align-items-center justify-content-center">
                    <div class="close-btn"><i class="icon-close"></i></div>
                    <div class="row d-flex justify-content-center">
                        <div class="col-md-8">
                            <form action="#">
                                <div class="form-group">
                                    <input type="search" name="search" id="search" placeholder="What are you looking for?">
                                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <!-- Navbar Brand -->
                <div class="navbar-header d-flex align-items-center justify-content-between">
                    <!-- Navbar Brand --><a href="http://127.0.0.1:8000" class="navbar-brand">Manoz's Blog</a>
                    <!-- Toggle Button-->
                    <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
                </div>
                <!-- Navbar Menu -->
<!--                 <div id="navbarcollapse" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a href="http://127.0.0.1:8000" class="nav-link ">Blog</a>
                        </li>
                    </ul>
                </div> -->
            </div>
        </nav>
    </header>
    {% block main %}
    {% endblock %}
        <div class="copyrights" style="background-color: black;color:white;padding-top: 20px;">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p>&copy; 2019. All rights reserved. Developed by <u>Manoz Acharya</u></p>
                    </div>
                </div>
            </div>
        </div>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
</body>

</html>

myblog/templates/myblog/latest_posts.html
                {% load static %}
                <div class="blog-posts">
                    {% for post in latest_posts %}
                    <a href="{{ post.get_absolute_url }}">
                        <div class="item d-flex align-items-center">
                            <div class="image"><img src="{{ post.image.url }}" alt="..." class="img-fluid"></div>
                            <div class="title"><strong>{{ post.title }}</strong>
                                <div class="d-flex align-items-center">
                                    <div class="comments"><i class="icon-comment"></i>{{ post.comments.count }}</div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </a></div>

myblog/templates/myblog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

myblog/templates/myblog/post.html
{% extends 'myblog/header.html' %}
{% load blog_tags %}
{% load static %}
{% block main %}
<div class="container">
    <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8">
            <div class="container">
                <div class="post-single">
                    <div class="post-thumbnail"><img src="{{ post.image.url }}" alt="..." class="img-fluid"></div>
                    <div class="post-details">
                        <div class="post-meta d-flex justify-content-between">
                            <div class="category"><a href="#">{{ post.category }}</a></div>
                        </div>
                        <h1>{{ post.title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
                        <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                                <div class="avatar"><img src="{% static 'img/avatar-1.jpg' %}" alt="..." class="img-fluid"></div>
                                <div class="title"><span>{{ post.author }}</span></div>
                            </a>
                            <div class="d-flex align-items-center flex-wrap">
                                <div class="date"><i class="icon-clock"></i> 2 months ago</div>
                                <div class="views"><i class="icon-eye"></i> 500</div>
                                <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comments.count }}</div>
                            </div>
                        </div>
                        <div class="post-body">
                            <p style="text-align: justify;">{{ post.body | markdown}}</p>
                        </div>
                        <!-- <div class="post-tags"><a href="#" class="tag">#Business</a><a href="#" class="tag">#Tricks</a><a href="#" class="tag">#Financial</a><a href="#" class="tag">#Economy</a></div> -->
                        <div class="post-tags">Tags:<a href="#" class="tag">{{ post.tags.all | join:", " }}</a></div>
                        <div class="mt-3">
                            <p style="text-align: center;border: 1px solid #c9c5c5;">
                                <a href="{% url 'myblog:post_share' post.id %}">
                                    SHARE THIS POST
                                </a>
                            </p>
                        </div>
                        <div class="post-comments">
                            <header>
                                {% with comments.count as total_comments %}
                                <h3 class="h6">Post Comment{{ total_comments | pluralize }}<span class="no-of-comments">({{ total_comments }})</span></h3>
                                {% endwith %}
                            </header>
                            <!--                             <div class="comment">
                                <div class="comment-header d-flex justify-content-between">
                                    <div class="user d-flex align-items-center">
                                        <div class="image"><img src="{% static 'img/user.svg' %}" alt="..." class="img-fluid rounded-circle"></div>
                                        <div class="title"><strong>Jabi Hernandiz</strong><span class="date">May 2016</span></div>
                                    </div>
                                </div>
                                <div class="comment-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                                </div>
                            </div>
                            <div class="comment">
                                <div class="comment-header d-flex justify-content-between">
                                    <div class="user d-flex align-items-center">
                                        <div class="image"><img src="{% static 'img/user.svg' %}" alt="..." class="img-fluid rounded-circle"></div>
                                        <div class="title"><strong>Nikolas</strong><span class="date">May 2016</span></div>
                                    </div>
                                </div>
                                <div class="comment-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                                </div>
                            </div>
                            <div class="comment">
                                <div class="comment-header d-flex justify-content-between">
                                    <div class="user d-flex align-items-center">
                                        <div class="image"><img src="{% static 'img/user.svg' %}" alt="..." class="img-fluid rounded-circle"></div>
                                        <div class="title"><strong>John Doe</strong><span class="date">May 2016</span></div>
                                    </div>
                                </div>
                                <div class="comment-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                                </div>
                            </div> -->
                            {% for comment in comments %}
                            <div class="comment">
                                <div class="comment-header d-flex justify-content-between">
                                    <div class="user d-flex align-items-center">
                                        <div class="title"><span class="date">Comment by {{comment.name }} {{ comment.created }}</span></div>
                                    </div>
                                </div>
                                <div class="comment-body">
                                    <p>{{ comment.body | linebreaks }}</p>
                                </div>
                            </div>
                            {% empty %}
                            <p> There are no comments yet. You may post your comment!</p>
                            {% endfor %}
                        </div>
                        <div class="add-comment">
                            <header>
                                <h3 class="h6">Leave a Comment</h3>
                            </header>
                            {% if new_comment %}
                            <strong>Your Comment Has Been Added.</strong>
                            {% else %}
                            <form action="." class="commenting-form" method="POST">
                                <!--                                 <div class="row">
                                    <div class="form-group col-md-6">
                                        <input type="text" name="username" id="username" placeholder="Name" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <input type="email" name="username" id="useremail" placeholder="Email Address (will not be published)" class="form-control">
                                    </div>
                                    <div class="form-group col-md-12">
                                        <textarea name="usercomment" id="usercomment" placeholder="Type your comment" class="form-control"></textarea>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <button type="submit" class="btn btn-secondary">Submit Comment</button>
                                    </div>
                                </div> -->
                                {{ comment_form.as_p }}
                                {% csrf_token %}
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-secondary">Submit Comment</button>
                                </div>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <aside class="col-lg-4">
            <!-- Widget [Latest Posts Widget]        -->
            <div class="widget latest-posts">
                <header>
                    <h3 class="h6">Latest Posts</h3>
                </header>
                {% show_latest_posts 3 %}
            </div>
            <div class="widget latest-posts">
                <header>
                    <h3 class="h6">Most Commented Posts</h3>
                </header>
                <div class="blog-posts">
                    {% get_most_commented_posts as most_commented_posts %}
                    {% for post in most_commented_posts %}
                    <a href="{{ post.get_absolute_url }}">
                        <div class="item d-flex align-items-center">
                            <div class="image"><img src="{{ post.image.url }}" alt="..." class="img-fluid"></div>
                            <div class="title"><strong>{{ post.title }}</strong>
                                <div class="d-flex align-items-center">
                                    <div class="comments"><i class="icon-comment"></i>{{ post.comments.count }}</div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </a></div>
            </div>
        </aside>
    </div>
</div>
{% endblock %}

myblog/templates/myblog/share.html
{% extends 'myblog/header.html' %}
{% load static %}
{% block main %}
	{% if sent %}
	<h3> E-Mail Successfully Sent</h3>
	<p>
		"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
	</p>
	{% else %}
	<div class="add-comment mb-5" style="text-align: center;">
		<center><h5 class="mt-5 mb-5">Share "{{ post.title }}" by e-mail</h5></center>
		<form action="." method="POST" class="commenting-form">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Send E-Mail">
		</form>
	</div>
		{% endif %}
{% endblock %}